### ISSUE TITLE
Integração vs Add-on

### ISSUE THREAD

**Issue by gamajunior** [mukaschultze/ha-aquecedor-rinnai#16]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/mukaschultze/ha-rinnai-heater/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Ficou muito feliz em saber que existe um projeto ativo para os aquecedores rinnai.
possuo um REU E271 com modulos ROU-0031, mas estou considerando trocar pelo ROU-004 já que o atual costuma desconfigurar e é muito dificil ficar reconfigurando tudo .

### Describe the solution you'd like

Pontos positivos da integração comparando com o addon:
- Identificou automaticamente o aquecedor;
- aparentemente possui todas as informações que o aquecedor fornece;
- os botões de alterar a temperatura funcionam, já do addon para com o tempo 

### Describe alternatives you've considered

Pontos que precisam melhorar para no meu caso substituir o addon e os fluxos complementares no nodered.

- o campo de temperatura deveria ser um compo number,  pois uso o nodered para ajustar a temperatura da agua dependendo da temperatura externa.
- não consegui alterar a temperatura com o aquecedor ligado, no addon ele seta o HA como prioridade e consigo mudar a temperatura.
- a opção de alterar a temperatura é de 0,5c onde deveria ser de 1c.
- a tela de configuração tem erros de tradução me parece.
- a entidade chama, funcionou no inicio, depois só fica off e agora fica como indisponível. 
- a entidade atações fica sempre em 43,900, mas me parece quem vem do /bus, pois lá não muda também.
- ao instalar algumas entidades vem desabilidatas, o que gerar trabalho desnecessário em ficar habilitando.
- - poderia tem um campo de tensão da instalação, com isso fazer um calculo automático para trazer o consumo em Watts o que ajuda na contabilização do consumo de energia.

<img width="642" alt="image" src="https://github.com/user-attachments/assets/8166f031-fed6-44d3-9ab7-adca16fa2deb">
<img width="574" alt="image" src="https://github.com/user-attachments/assets/b97b8899-be0f-4e1f-90c5-67fce5b32f66">
<img width="542" alt="image" src="https://github.com/user-attachments/assets/adfff1a1-84ba-405e-af0a-2fc2123fbc4a">
<img width="254" alt="image" src="https://github.com/user-attachments/assets/ce72f862-50e4-43c4-9842-51020505b134">

fluxo que ajusta a temperatura da agua dependendo do clima atual.
<img width="829" alt="image" src="https://github.com/user-attachments/assets/056d0d56-69b3-42fa-aab9-d0f1a06a80cd">

### Additional context

não consegui testar muito a integração pois a addon ainda supri algumas necessidades que essa integração ainda não atende.

**Comment by mukaschultze** [comment]
> * o campo de temperatura deveria ser um compo number,  pois uso o nodered para ajustar a temperatura da agua dependendo da temperatura externa.

NodeRED não consegue ajustar se não for number? O `water_heater` expõe serviços para mudar a temperatura igual um `climate`, não sei se isso ajuda ou não, tenho zero experiencia em NodeRED.

> * não consegui alterar a temperatura com o aquecedor ligado, no addon ele seta o HA como prioridade e consigo mudar a temperatura.

Sim, ainda não implementei a questão da prioridade, mas ainda vou.

> * a opção de alterar a temperatura é de 0,5c onde deveria ser de 1c.

Fiz um PR no hass/core pra corigir isso mas recusaram 

> * a tela de configuração tem erros de tradução me parece.

To sabendo, primeira vez integrando tradução e tem feature que pelo visto não funciona pra integração customizada.

> * a entidade chama, funcionou no inicio, depois só fica off e agora fica como indisponível.

Tem que ir na configuração do dispositivo no HomeAssistant e mudar o tempo de varredura do endpoint `tela` pra algo maior que zero. Eu deixei em zero (desligado) por padrão pq percebi que se ficar acessando esse endpoint depois de um tempo o consumo da agua e gás bugam e só voltam a funcionar na semana seguinte.

> * a entidade atações fica sempre em 43,900, mas me parece quem vem do /bus, pois lá não muda também.

Atualiza de 100 em 100.

> * ao instalar algumas entidades vem desabilidatas, o que gerar trabalho desnecessário em ficar habilitando.

Isso ai é de propósito, são boas práticas do HomeAssistant pra não ficar floodando o banco de dados com coisa irrelevante pra maioria dos usuários. 

> * * poderia tem um campo de tensão da instalação, com isso fazer um calculo automático para trazer o consumo em Watts o que ajuda na contabilização do consumo de energia.

O campo de corrente não é a corrente da tomada e sim do modulador de chama em 12V. Multiplicar ele por 220 não da a potencia que o aquecedor ta puxando da tomada (apesar de serem valores bem próximos puramente por sorte).

**Comment by gamajunior** [comment]
> > * o campo de temperatura deveria ser um campo number,  pois uso o nodered para ajustar a temperatura da agua dependendo da temperatura externa.
> 
> NodeRED não consegue ajustar se não for number? O `water_heater` expõe serviços para mudar a temperatura igual um `climate`, não sei se isso ajuda ou não, tenho zero experiencia em NodeRED.

Você tem razão, funcionou

<img width="722" alt="image" src="https://github.com/user-attachments/assets/5908c44e-c651-44ea-b378-1c6d3948b8de">

**Comment by gamajunior** [comment]
> > * não consegui alterar a temperatura com o aquecedor ligado, no addon ele seta o HA como prioridade e consigo mudar a temperatura.
> 
> Sim, ainda não implementei a questão da prioridade, mas ainda vou.
> 

Essa sim é uma configuração crítica no meu caso, pois ao ligar o aquecedor o HA me pergunta se quero ajustar a temperatura, para quem for tomar banho mudar da temperatura automática (uso uma skill que se chama "me pergunte")

> > * a opção de alterar a temperatura é de 0,5c onde deveria ser de 1c.
> 
> Fiz um PR no hass/core pra corigir isso mas recusaram
> 

Uma pena, pois na UI fica estranho, outra coisa me parece que fica um "ponto" em 37 é alguma configuração?

> > * a tela de configuração tem erros de tradução me parece.
> 
> To sabendo, primeira vez integrando tradução e tem feature que pelo visto não funciona pra integração customizada.
> 

Não é crítico, mas seria legal ajustar

> > * a entidade chama, funcionou no inicio, depois só fica off e agora fica como indisponível.
> 
> Tem que ir na configuração do dispositivo no HomeAssistant e mudar o tempo de varredura do endpoint `tela` pra algo maior que zero. Eu deixei em zero (desligado) por padrão pq percebi que se ficar acessando esse endpoint depois de um tempo o consumo da agua e gás bugam e só voltam a funcionar na semana seguinte.
> 

Testando

> > * a entidade atações fica sempre em 43,900, mas me parece quem vem do /bus, pois lá não muda também.
> 
> Atualiza de 100 em 100.

Não sabia

> 
> > * ao instalar algumas entidades vem desabilidatas, o que gerar trabalho desnecessário em ficar habilitando.
> 
> Isso ai é de propósito, são boas práticas do HomeAssistant pra não ficar floodando o banco de dados com coisa irrelevante pra maioria dos usuários.
> 

Não sabia

**Comment by gamajunior** [comment]
> > * * poderia tem um campo de tensão da instalação, com isso fazer um calculo automático para trazer o consumo em Watts o que ajuda na contabilização do consumo de energia.
> 
> O campo de corrente não é a corrente da tomada e sim do modulador de chama em 12V. Multiplicar ele por 220 não da a potencia que o aquecedor ta puxando da tomada (apesar de serem valores bem próximos puramente por sorte).

também não sabia, mas uso para calcular o consumo de energia do meu apartamento

**Comment by gamajunior** [comment]
Muka, estou implementando a integração e uma coisa me chmou a atenção, a temp setada fica "quebrada" porém o nr deveria ser inteiro.
Sabe como corrigir? tentei pegar a temperatura da entidade water_heater.cozinha_aquecedor porém ela não traz o valor da temperatura atual e sim "gas" na payload.

<img width="722" alt="image" src="https://github.com/user-attachments/assets/b7be6c1e-e5c6-4feb-ab56-27eb2ba5b79d">


<img width="776" alt="image" src="https://github.com/user-attachments/assets/62e3546e-0d2b-43e4-bbde-b9820ef6f861">

**Comment by gamajunior** [comment]
Muka, mais um ponto que identifiquei aqui, no addon tem a opção de desligar o aquecedor, mas na integração não tem.

**Comment by mukaschultze** [comment]
@gamajunior 

> Essa sim é uma configuração crítica no meu caso, pois ao ligar o aquecedor o HA me pergunta se quero ajustar a temperatura, para quem for tomar banho mudar da temperatura automática (uso uma skill que se chama "me pergunte")

Implementei o negócio da prioridade na versão 0.1.7. Tem que ativar nas configurações o "prioridade automática" pra funcionar. Deixei opt-in por enquanto pq não sei quais os efeitos colaterais.

> Uma pena, pois na UI fica estranho, outra coisa me parece que fica um "ponto" em 37 é alguma configuração?

Não entendi o que tu quis dizer com "um ponto", consegue mandar um print? Eu fiz uma gambiarra e consegui corrigir o bug de aumentar a temperatura de meio grau em meio grau, agora sobe certo de 1 em 1.

> Não é crítico, mas seria legal ajustar

Corrigido

> Sabe como corrigir? tentei pegar a temperatura da entidade water_heater.cozinha_aquecedor porém ela não traz o valor da temperatura atual e sim "gas" na payload.

Acho que isso ai é o que teu controlador ta reportando mesmo. Esse sensor do temperatura setada não tem nenhuma magica, a integração só mostra o que ta recebendo do controlador. A temperatura no water_heater sim é calculada com base na temperatura "crua", deve ser por isso que tu ta vendo essa diferença. O que mostra no teu app da Rinnai? No meu a temperatura setada tem um pequeno atraso mas mostra o msm valor que no water_heater.

Tu consegue pegar a temperatura do water_heater usando esse template `state_attr("water_heater.e21_heater", "temperature")`

> Muka, mais um ponto que identifiquei aqui, no addon tem a opção de desligar o aquecedor, mas na integração não tem.

Tem como mudar o modo de operação de Gás pra Desligado no heater e no card de tile:

![image](https://github.com/user-attachments/assets/ae5e303f-2978-45f2-960c-57425a9a9785)

![image](https://github.com/user-attachments/assets/88fd0821-e580-4ae8-96f1-325f88dffbb3)

**Comment by gamajunior** [comment]
> Implementei o negócio da prioridade na versão 0.1.7. Tem que ativar nas configurações o "prioridade automática" pra funcionar. Deixei opt-in por enquanto pq não sei quais os efeitos colaterais.
> 
> >

Fiz a atualização e habilitei a opção de "prioridade automática", testei e funcionou, mas notei que tem um certo delay, capturei a tela para tentar reproduzir o que ocorre. me parece que ele espera o tempo da próxima atualização "coloquei 5 segundos"


https://github.com/user-attachments/assets/123fcf28-d7b6-49ac-8338-519474b980dd

**Comment by gamajunior** [comment]
> Não entendi o que tu quis dizer com "um ponto", consegue mandar um print? Eu fiz uma gambiarra e consegui corrigir o bug de aumentar a temperatura de meio grau em meio grau, agora sobe certo de 1 em 1.
> 
> >

não consegui replicar :(, então entendo que está OK

**Comment by gamajunior** [comment]
> Tem como mudar o modo de operação de Gás pra Desligado no heater e no card de tile:
> 
> ![image](https://private-user-images.githubusercontent.com/13923364/389130059-ae5e303f-2978-45f2-960c-57425a9a9785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzAyNTYsIm5iZiI6MTczMjM2OTk1NiwicGF0aCI6Ii8xMzkyMzM2NC8zODkxMzAwNTktYWU1ZTMwM2YtMjk3OC00NWYyLTk2MGMtNTc0MjVhOWE5Nzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDEzNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZjExZmM2Y2QyZDIwYTQ5YmQ3ZGM2OTYwZTE5MmE1ZGQ0OTNiZTJkNmEyNTlkYWQ5MTMzZWVlZjE2Nzg3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fwo9f9g7FYrG39wtJmavF-xIcjjjS1PqK-BXzXmJXTg)
> 
> ![image](https://private-user-images.githubusercontent.com/13923364/389129716-88fd0821-e580-4ae8-96f1-325f88dffbb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzAyNTYsIm5iZiI6MTczMjM2OTk1NiwicGF0aCI6Ii8xMzkyMzM2NC8zODkxMjk3MTYtODhmZDA4MjEtZTU4MC00YWU4LTk2ZjEtMzI1Zjg4ZGZmYmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDEzNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OWRmZWRkNTIwM2QzZjg5MGVlMmJhNmUzN2U1NTExOWFkNGRlMmJiMzQ1ZTI0OGY2NzIxM2M1MzBiOWZhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RNb-7CJoWCqc5YmokhcCkn1oedDbjDz7x8-4r776xP8)

faz sentido, só não consegui colocar esse card que vc printou

<img width="614" alt="image" src="https://github.com/user-attachments/assets/1df21eac-8226-4f30-9260-d5ef4c32a8ed">

<img width="624" alt="image" src="https://github.com/user-attachments/assets/5967a4a5-d901-4d4d-83ef-dfd1fab92900">

**Comment by gamajunior** [comment]
Mais uma vez obrigado pela ajuda :)

**Comment by mukaschultze** [comment]
@gamajunior 

> 
> faz sentido, só não consegui colocar esse card que vc printou
> 
>

```yaml
features:
  - type: target-temperature
  - type: water-heater-operation-modes
type: tile
entity: water_heater.e21_heater
show_entity_picture: false
vertical: false
state_content:
  - state
  - current_temperature
```

**Comment by gamajunior** [comment]
Notei um ponto aqui, a entidade switch.cozinha_aquecedor_prioridade por vezes não liga automaticamente, mas me parece que a prioridade ainda sim funciona.

**Desligado**
<img width="275" alt="image" src="https://github.com/user-attachments/assets/e94221d0-a00c-48b2-bfd0-e45fbfbbae7a">

**Ligado**
<img width="266" alt="image" src="https://github.com/user-attachments/assets/5bca3ca8-29fc-479f-885a-81b62bf6fe7a">

**Comment by gamajunior** [comment]
> @gamajunior
> 
> > faz sentido, só não consegui colocar esse card que vc printou
> 
> ```yaml
> features:
>   - type: target-temperature
>   - type: water-heater-operation-modes
> type: tile
> entity: water_heater.e21_heater
> show_entity_picture: false
> vertical: false
> state_content:
>   - state
>   - current_temperature
> ```

Show


<img width="226" alt="image" src="https://github.com/user-attachments/assets/05a3879a-2a2e-4755-a448-6cf24d2e2d0e">


<img width="665" alt="image" src="https://github.com/user-attachments/assets/4d7bdb63-76eb-4457-b62b-0436c0946b5a">

**Comment by mukaschultze** [comment]
> Notei um ponto aqui, a entidade switch.cozinha_aquecedor_prioridade por vezes não liga automaticamente, mas me parece que a prioridade ainda sim funciona.
> 

É por causa do delay que tem no switch, ele liga e desliga muito rapido quando troca a temperatura ai o switch não acompanha. Vou ver se consigo tirar esse delay

**Comment by gamajunior** [comment]
se querer repliquei o delay e a entidade setada ficou quebrada, olha isso.

<img width="398" alt="image" src="https://github.com/user-attachments/assets/7a11cffa-ea6c-4e2e-8331-71bd1ad225fd">


https://github.com/user-attachments/assets/410cfcba-878b-4590-a807-9948d33b27c1

**Comment by mukaschultze** [comment]
> se querer repliquei o delay e a entidade setada ficou quebrada, olha isso.
> 

Consegue mandar o arquivo gerado por esse menu? 

![image](https://github.com/user-attachments/assets/28c95a8e-e0c2-4dc1-ae8e-082c1da123ea)

**Comment by gamajunior** [comment]
> > se querer repliquei o delay e a entidade setada ficou quebrada, olha isso.
> 
> Consegue mandar o arquivo gerado por esse menu?
> 
> ![image](https://private-user-images.githubusercontent.com/13923364/389205617-28c95a8e-e0c2-4dc1-ae8e-082c1da123ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzQzODcsIm5iZiI6MTczMjM3NDA4NywicGF0aCI6Ii8xMzkyMzM2NC8zODkyMDU2MTctMjhjOTVhOGUtZTBjMi00ZGMxLWFlOGUtMDgyYzFkYTEyM2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyN2UzYTAyNjZiYjY2MjA0ZGNhZDVjMDcwOGNjNzUwMWU1Nzc1NmMxMTFlNmJlZDQ3MjVlZGRmNmI5YjgzMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-b5XxSzIqGnMlIXRZm7dYrENEA25nxmnZAMr_9e32RI)

claro

[config_entry-rinnai-01JCSES4NFH7R6HQQ24K5V4872.json](https://github.com/user-attachments/files/17880168/config_entry-rinnai-01JCSES4NFH7R6HQQ24K5V4872.json)

**Comment by mukaschultze** [comment]
No controlador e no sensor tão ambos com 37.00, acho que é só tua interface que ta mostrando uma média mesmo, não sei pq.

```json
"target_temperature": "3700",
```

```json
"sensor.cozinha_aquecedor_temperatura_setada": {
  "name": null,
  "original_name": "Temperatura setada",
  "disabled": false,
  "disabled_by": null,
  "entity_category": null,
  "device_class": null,
  "original_device_class": "temperature",
  "icon": null,
  "original_icon": null,
  "unit_of_measurement": "\u00b0C",
  "state": {
    "state": "37.0",
    "attributes": {
      "state_class": "measurement",
      "unit_of_measurement": "\u00b0C",
      "device_class": "temperature",
      "friendly_name": "COZINHA Aquecedor Temperatura setada"
    },
    "last_changed": "2024-11-23T14:57:19.252192+00:00",
    "last_reported": "2024-11-23T14:57:19.252192+00:00",
    "last_updated": "2024-11-23T14:57:19.252192+00:00"
  }
},
```

**Comment by mukaschultze** [comment]
Aparentemente todos os problemas citados aqui foram resolvidos exceto o arredondamento que parece ser algo no frontend do home assistant e não na integração.

Vou fechar a issue, se tiver mais alguma coisa pra reportar favor abrir uma nova issue.

Muito obrigado pelo feedback!

**Comment by mukaschultze** [comment]
Pra referência futura: O "bug" de mostrar uma temperatura setada maior que a temperatura que o usuário configurou acontece quando a temperatura de entrada da água é muito alta. Acho que o aquecedor tem uma capacidade minima que consegue aquecer, e pra não ficar desligando a chama ele põe a temperatura um pouco mais alta.

Notei que isso acontece em dias bem quentes com a temperatura setada baixa. No print abaixo da pra ver que subtraindo a temperatura setada pela temperatura de entrada da exatamente 7.5°C, o minimo que o aquecedor consegue esquentar.

![Image](https://github.com/user-attachments/assets/4dfe0d91-fd8e-4a9d-83b7-22d34d5aeff7)
